In [216]:
import pandas as pd

In [217]:
# Creating the dictionary
dict1 = {
    'Name': ['Priyang', 'Aadhya', 'Krisha', 'Vedant', 'Parshv', 'Mittal', 'Archana'],
    'Marks': [98, 89, 99, 87, 90, 83, 99],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female']
}

# Creating the DataFrame
df = pd.DataFrame(dict1)

# Displaying the DataFrame
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 1. Display Top 3 Rows of The Dataset

In [218]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

### 2. Display last 3 Rows of The Dataset

In [219]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 3. Find Shape of Our Dataset (Number of Rows and Number of Columns)

In [220]:
df.shape

(7, 3)

In [221]:
print("Number of Rows :-  " , df.shape[0])

Number of Rows :-   7

In [222]:
print("Number of columns :- " , df.shape[1])

Number of columns :-  3

### 4. Get information About our Dataset

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 296.0+ bytes

### 5. Check Null Value in The Dataset

In [224]:
df.isnull().sum(axis=0)  # 0 mean vertical and 1 mean horizontal

Name      0
Marks     0
Gender    0
dtype: int64

### 6. Get Overall Statics About The Dataframe

In [225]:
df.describe(include= 'all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

### 7. Find Unique value From The Gender Column

In [226]:
df['Gender'].unique()  # this tell you how many diffferent values are here there are 2 male and female

array(['Male', 'Female'], dtype=object)

### 8. Find the Number of Unique value From The Gender Column

In [227]:
df['Gender'].nunique()

2

### 9. Display Count of Unique Value in Gender Column

In [228]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

### 10. Find Total Number of Student Having Marks Between 90 To 100 (inclusive) Using Between Method

In [229]:
df[df["Marks"]>90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99  Female

In [230]:
len (df[(df['Marks']>=90) & (df['Marks']<=100 )])

4

In [231]:
sum(df['Marks'].between(90,100))

4

### 11. Find Average Marks

In [232]:
print(df["Marks"].mean())

92.14285714285714

In [233]:
df['Marks']

0    98
1    89
2    99
3    87
4    90
5    83
6    99
Name: Marks, dtype: int64

### 12. Apply Method

In [234]:
def marks(x):
    return x/2

In [235]:
df['Marks'].apply(marks)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [236]:
df['Half_Marks'] = df['Marks'].apply(marks)
df

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [237]:
df['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

### 13. Map Function

In [238]:
df['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [239]:
df['Male_Female'] = df ['Gender'].map({'Male' : 1 , 'Female' : 0 })
df

      Name  Marks  Gender  Half_Marks  Male_Female
0  Priyang     98    Male        49.0            1
1   Aadhya     89  Female        44.5            0
2   Krisha     99  Female        49.5            0
3   Vedant     87    Male        43.5            1
4   Parshv     90    Male        45.0            1
5   Mittal     83  Female        41.5            0
6  Archana     99  Female        49.5            0

### 14. Drop Column

In [240]:
df= df.drop('Male_Female', axis=1) 
df

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [241]:
# df= df.drop(['Male_Female','Name'] , axis=1)  # to drop more column in one

In [242]:
df

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

### 15. Print Name of the Columns

In [243]:
df.columns

Index(['Name', 'Marks', 'Gender', 'Half_Marks'], dtype='object')

### 16. Sort The Dataframe As Per The Marks Column

In [247]:
df.sort_values(by=['Marks','Gender'],ascending=False)

      Name  Marks  Gender  Half_Marks
2   Krisha     99  Female        49.5
6  Archana     99  Female        49.5
0  Priyang     98    Male        49.0
4   Parshv     90    Male        45.0
1   Aadhya     89  Female        44.5
3   Vedant     87    Male        43.5
5   Mittal     83  Female        41.5

### 17. Display Name and Marks of The Female Students

In [253]:
df

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [261]:
df[df['Gender']=='Female' ][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99

In [263]:
df[df['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99